apiVersion: agones.dev/v1
kind: Fleet

metadata:
  name: xonotic
  namespace: default

spec:
  replicas: 2

  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 26000

      template:
        spec:
          containers:
            - name: xonotic
              image: us-docker.pkg.dev/agones-images/examples/xonotic-example:2.8